### ISSUE TITLE
Number line picker inaccurate

### ISSUE THREAD

**Issue by setphen** [patriciogonzalezvivo/glslEditor#1]
Using the latest version of Chome [Version 48.0.2564.97 (64-bit)]
Also reproduced in Firefox v. 42.0

When I click on the number picker (white indicator arrow) I get a value that lies outside of the line.

<img width="353" alt="screen shot 2016-02-03 at 6 39 05 pm" src="https://cloud.githubusercontent.com/assets/3891632/12800798/b83e69b6-caa5-11e5-866d-0dfb47106406.png">

**Comment by patriciogonzalezvivo** [comment]
Fixed: https://github.com/patriciogonzalezvivo/glslEditor/commit/58093fb3c811a948f65350342ca5e221caadcc7f

**Comment by patriciogonzalezvivo** [comment]
not really : (

**Comment by patriciogonzalezvivo** [comment]
https://github.com/patriciogonzalezvivo/glslEditor/commit/18ad50a2b357ccda3fd3e32e4cd98fb27a5d2468

done!
