### ISSUE TITLE
Add a getFileName function

### ISSUE THREAD

**Issue by brucelane** [patriciogonzalezvivo/glslEditor#11]
I will do that in my fork then I'll do a PR!    
getFileName() {
        let content = this.getContent();
        let result = content.match(/\/\/\s*[F|f]ilename\s*:\s*([\w|\s|\@|\(|\)|\-|\_]*)/i);
        console.log(result);
        if (result && !(result[1] === ' ' || result[1] === '')) {
            let filename = result[1].replace(/(\r\n|\n|\r)/gm, '');
            return filename;
        }
        else if (this.bufferManager !== undefined) {
            return this.bufferManager.current;
        }
        else {
            return 'unknown';
        }
    }

**Comment by patriciogonzalezvivo** [comment]
Not sure what it do?

**Comment by brucelane** [comment]
like getTitle or getAuthor, I need it to get the filename to save on the C++ part when it's received

**Comment by brucelane** [comment]
I could store it in "Title" though, so no coding required...

**Comment by patriciogonzalezvivo** [comment]
haaa that's a great idea

**Comment by brucelane** [comment]
sorry, it was more a note to myself as I'm reverting back to u_* uniform names...

**Comment by patriciogonzalezvivo** [comment]
The defines system should be something like this:

```glsl
#define iTime u_time
#define iMouse u_mouse
#define iResolution u_resolution
#define iDate u_date
```

**Comment by brucelane** [comment]
yes, I've seen there is a frag_header where I can put those lines...

**Comment by patriciogonzalezvivo** [comment]
: )
