### ISSUE TITLE
Link Button from Color Picker doesn't work

### ISSUE THREAD

**Issue by alijaya** [patriciogonzalezvivo/glslEditor#36]
It's because the name changing from link_button to linkButton

**Comment by patriciogonzalezvivo** [comment]
Seams a consecuence of this commit https://github.com/patriciogonzalezvivo/glslEditor/commit/62dfc42c7cb0b4d9d4261db7b364d4d93831b959.

@RoryO do you mind fixing this one?

**Comment by RoryO** [comment]
Shoot. Sorry. I’ll look this evening.

**Comment by alijaya** [comment]
Hey I've made some correction.

**Comment by patriciogonzalezvivo** [comment]
Yay! thanks both!
