### ISSUE TITLE
Export / Artwork URL ... not working on Firefox

### ISSUE THREAD

**Issue by yvan-sraka** [patriciogonzalezvivo/glslEditor#38]
Hello,

On http://editor.thebookofshaders.com/, when I click on `Export` / `Artwork URL ...`, I get no pop-up and this error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://thebookofshaders.com:8080/save. (Reason: CORS request did not succeed).
```

I also create an issue here https://github.com/webcompat/web-bugs/issues/16659

Thank's you in advance,

**Comment by patriciogonzalezvivo** [comment]
Thanks! This have been coming back over and over. I don’t really understand what’s wrong.

**Comment by alijaya** [comment]
Not working also in chrome

**Comment by GarmOfGnipahellir** [comment]
You can bypass it by trying to access the address in the error in a new tab and adding a security exception for it.
Worked for me at least (on Firefox)! 🙂

**Comment by Merlinstail** [comment]
> Thanks! This have been coming back over and over. I don’t really understand what’s wrong.
> […](#)
> On Apr 29, 2018, at 1:46 AM, Yvan Sraka ***@***.***> wrote: Hello, On http://editor.thebookofshaders.com/, when I click on Export / Artwork URL ..., I get no pop-up and this error : Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://thebookofshaders.com:8080/save. (Reason: CORS request did not succeed). I also create an issue here [webcompat/web-bugs#16659](https://github.com/webcompat/web-bugs/issues/16659) Thank's you in advance, — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hopefully this helps:

> The certificate for thebookofshaders.com:8080 expired on 02/09/2020.
