### ISSUE TITLE
Save functionality blocked by server

### ISSUE THREAD

**Issue by kylestew** [patriciogonzalezvivo/glslEditor#4]
Seeing this in the console logs on Chrome whenever I try to generate a link to send to my Openframe.

![screen shot 2016-05-02 at 12 41 58 pm](https://cloud.githubusercontent.com/assets/251119/14965642/5b8705f8-1063-11e6-9803-4624014dc125.png)

**Comment by patriciogonzalezvivo** [comment]
sorry, server crash.... try again

**Comment by kylestew** [comment]
All good, thanks for the quick response!

**Comment by cimi** [comment]
This seems to be happening again:

```
share.js:46 POST https://thebookofshaders.com:8080/save net::ERR_CONNECTION_TIMED_OUT
saveOnServer @ share.js:46
(anonymous) @ ExportModal.js:22
```

Thank you for these great tools!
