### ISSUE TITLE
console error when using frag_header

### ISSUE THREAD

**Issue by actarian** [patriciogonzalezvivo/glslEditor#43]
There's a console error on init a glslEditor with the frag_header option.
It could be avoided changing line 29 of `Shader.js` 

from

`this.elCanvas.setAttribute('data-fragment', this.options.frag);`
        
to

`this.elCanvas.setAttribute('data-fragment', this.options.frag_header + this.options.frag + this.options.frag_footer);`

**Comment by patriciogonzalezvivo** [comment]
Ohh good spot. I will take a look to it!

**Comment by patriciogonzalezvivo** [comment]
Done https://github.com/patriciogonzalezvivo/glslEditor/commit/5c83c60df59620e95433d68773088b9afe96ed6c

Thanks for the heads up
