### ISSUE TITLE
Recent malfunction on the web version

### ISSUE THREAD

**Issue by riccardoscalco** [patriciogonzalezvivo/glslEditor#44]
Hi, I am using a lot the editor at http://editor.thebookofshaders.com/.

Unfortunately recently I noted a malfunction, my shaders do not work anymore.
I can open the editor and the initial shader is visible, but if I change the code the canvas is not updated.

The following shader for example does not work:
```
#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;

void main() {
	vec2 st = gl_FragCoord.xy/u_resolution;
	gl_FragColor = vec4(st, 1., 1.);
}
``` 

I tested the editor in Chrome, Safari and Firefox in macos.

Thanks for your work, I really appreciate.

**Comment by patriciogonzalezvivo** [comment]
Hi @riccardoscalco, I think I know where the problem originates... what happen if you change the size of the viewport? 

Yesterday I detect a bug on GlslCanvas where doesn't render shader with no animation. The lack of u_time or u_mouse usually triggers a flag where the shader is only rendered when something change... and not constantly. I will take a look to that today

**Comment by riccardoscalco** [comment]
Probably your intuition is correct, this code works as expected:

```
#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform float u_time;

void main() {
    vec2 st = gl_FragCoord.xy/u_resolution;
    gl_FragColor = vec4(st, 1.0, u_time);
}
```

There is no hurry on my side, thanks for the effort.

**Comment by harryslotwiner** [comment]
Hey, just wanted to +1 this and say I'm experiencing the issue too. A quick work around I realized, as you mentioned, is to add u_time somewhere. Doesn't even need to be in code, can be in a comment. So for now I'm just adding it to the top of my shaders like this: 
```
//u_time

#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform float u_time;

void main() {
    vec2 st = gl_FragCoord.xy/u_resolution;
    gl_FragColor = vec4(st, 0.0, 1.0);
}
```

**Comment by patriciogonzalezvivo** [comment]
Hi! sorry for this regression. I'll work on it

**Comment by riccardoscalco** [comment]
@patriciogonzalezvivo I confirm, it works. Thanks!
