### ISSUE TITLE
backbuffer uniform

### ISSUE THREAD

**Issue by Chosko** [patriciogonzalezvivo/glslEditor#47]
Is there a way to get the backbuffer as a sampler2D uniform?

**Comment by patriciogonzalezvivo** [comment]
Hi! glslEditor share most of the features that glslViewer... please take a look on how to use multiple buffers using #define BUFFER0, BUFFER1, etc... https://github.com/patriciogonzalezvivo/glslViewer

**Comment by Chosko** [comment]
Thank you!
